package org.demo.loan.util;

public final class SQLQueries {

    public final static String QUERY_INSERT_APPLICATION = "INSERT INTO LOANAPPLICATION (REFERENCE_NO,CUSTOMER_ID,TYPE,AMOUNT,PERIOD,STATUS) VALUES(?,?,?,?,?,?)";
    public final static String QUERY_CHECK_APPLICATION_STATUS = "SELECT STATUS FROM LOANAPPLICATION WHERE REFERENCE_NO=?";
    public final static String QUERY_GET_ALL_APPLICATION = "SELECT * FROM LOANAPPLICATION";
    public final static String QUERY_CHECK_MAX_APPLICATIONID = "SELECT ID FROM LOANAPPLICATION ORDER BY ID DESC LIMIT 1;";
    public final static String QUERY_UPDATE_APPLICATION_STATUS = "UPDATE LOANAPPLICATION SET STATUS=? WHERE REFERENCE_NO=?";

}
